import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../componentes/providers";
import TopNav from "@/componentes/TopNav";


export const metadata: Metadata = {
  title: "Next Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
